name: wik_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-313.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  oauth2_client: ^3.2.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
